# This is a basic workflow to help you get started with Actions

name: Build Visual Studio evaluation period extender

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: windows-latest
    #env: 
      #msbuild: "C:\\Program Files (x86)\\Microsoft Visual Studio\\2019\\Enterprise\\MSBuild\\Current\\Bin"

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      #- name: Env variables
        #run:
         # echo “::add-path::C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\MSBuild\Current\Bin"
          
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
        name: Checkout code

      # Runs a single command using the runners shell
      - name: Setup MSBuild.exe
        uses: microsoft/setup-msbuild@v1.0.2

      - name: Build and Publish App
        run: msbuild VisualStudioEvalExtender.sln /p:Configuration=Release

      # Runs a set of commands using the runners shell
      - name: Upload Artifact
        uses: actions/upload-artifact@v1.0.0
        with:
          name: published_app
          path: bin\Release\
